// import 'dart:html';
import 'dart:convert';
import 'dart:ui';
// import 'package:flutter/gestures.dart';
// import 'package:be_healthy1/main.dart';
import 'package:flutter/material.dart';
import 'package:audioplayers/audioplayers.dart';
import 'package:audioplayers/src/audio_cache.dart';

// import 'package:http/http.dart' as http;
// import 'package:shared_preferences/shared_preferences.dart';
// import 'dart:convert';
import 'dart:async';
import 'package:be_healthy1/models/get.dart';
import 'package:get/get.dart';
import 'package:video_player/video_player.dart';
import 'package:carousel_slider/carousel_slider.dart';
// import 'dart:convert';
import 'package:intl/intl.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';
import 'package:be_healthy1/shared/shared.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:be_healthy1/models/channels_model.dart';
import 'package:be_healthy1/models/video_models.dart';
import 'package:be_healthy1/services/api_services.dart';
import 'package:be_healthy1/utilities/keys.dart';
import 'package:http/http.dart' as http;

// music
// import 'package:fluttertoast/fluttertoast.dart';
// import 'package:audioplayers/audioplayers.dart';
// import 'package:audioplayers/src/audio_cache.dart';

// import 'page_splash.dart';
// import 'package:assets_audio_player/assets_audio_player.dart';
// import 'package:video_player/video_player.dart';
// import 'package:chewie/chewie.dart';
// import 'package:chewie/src/chewie_player.dart';

part '../widget/inputfield.dart';
part '../widget/header.dart';
part 'video_screen.dart';
// part '../widget/button.dart';
part '../widget/card.dart';
// part 'video-player.dart';
part 'Olahraga.dart';
part 'video_page.dart';
part 'artikel_menu.dart';
part 'video_player.dart';
// // part 'timer.dart';
// part 'olahraga.dart';
// part 'OlahragaRingan.dart';
part 'olahraga_item.dart';
part 'coba.dart';
part 'page_splash.dart';
// part 'home.dart';
part 'music_player.dart';
part 'questions.dart';
part 'Playlist_menu.dart';
part 'onboarding.dart';
// // part 'GetData.dart';
part 'yoga.dart';
part 'music.dart';
part 'artikel.dart';
part 'profil.dart';
// part 'googleMaps.dart';
